-- CreateTable
CREATE TABLE `mls_listings` (
    `listingKey` VARCHAR(191) NOT NULL,
    `listingId` VARCHAR(191) NOT NULL,
    `standardStatus` VARCHAR(191) NOT NULL,
    `propertyType` VARCHAR(191) NOT NULL,
    `propertySubType` VARCHAR(191) NULL,
    `listPrice` DECIMAL(15, 2) NULL,
    `originalListPrice` DECIMAL(15, 2) NULL,
    `closePrice` DECIMAL(15, 2) NULL,
    `closeDate` DATETIME(3) NULL,
    `listingContractDate` DATETIME(3) NULL,
    `daysOnMarket` INTEGER NULL,
    `address` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `county` VARCHAR(191) NULL,
    `postalCode` VARCHAR(191) NULL,
    `latitude` DOUBLE NULL,
    `longitude` DOUBLE NULL,
    `bedrooms` INTEGER NULL,
    `bathrooms` INTEGER NULL,
    `livingArea` INTEGER NULL,
    `lotSizeAcres` DECIMAL(12, 4) NULL,
    `yearBuilt` INTEGER NULL,
    `hoaMonthly` DECIMAL(10, 2) NULL,
    `taxAnnual` DECIMAL(12, 2) NULL,
    `taxYear` INTEGER NULL,
    `poolPrivate` BOOLEAN NULL,
    `zoning` VARCHAR(191) NULL,
    `floodZone` VARCHAR(191) NULL,
    `leaseRestrictions` BOOLEAN NULL,
    `minimumLease` VARCHAR(191) NULL,
    `waterSource` VARCHAR(191) NULL,
    `sewer` VARCHAR(191) NULL,
    `utilities` TEXT NULL,
    `lotFeatures` TEXT NULL,
    `publicRemarks` TEXT NULL,
    `listOfficeName` VARCHAR(191) NULL,
    `listAgentFullName` VARCHAR(191) NULL,
    `mlgCanUse` VARCHAR(191) NULL,
    `modificationTimestamp` DATETIME(3) NOT NULL,
    `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `mls_listings_county_idx`(`county`),
    INDEX `mls_listings_standardStatus_idx`(`standardStatus`),
    INDEX `mls_listings_firstSeenAt_idx`(`firstSeenAt`),
    INDEX `mls_listings_listingContractDate_idx`(`listingContractDate`),
    PRIMARY KEY (`listingKey`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

